### ISSUE TITLE
你好，用Creator1.4.2打开拉下来的代码提示这个错误

### ISSUE THREAD

**Issue by kingkamg** [czlbaiyi/zergnest_client_creator#2]
TypeError: Cannot read property 'navigator' of undefined
at Object.goog.labs.userAgent.util.getNavigator_: "goog.crypt.xorByteArray=function(a,b){goog.asserts.assert(a.length==b.length,"XOR array lengths must match");for(var c=[],d=0;d<a.length;d++)c.push(a[d]^b[d]);return c};goog.labs={};goog.labs.userAgent={};goog.labs.userAgent.util={};goog.labs.userAgent.util.getNativeUserAgentString_=function(){var a=goog.labs.userAgent.util.getNavigator_();return a&&(a=a.userAgent)?a:""};goog.labs.userAgent.util.getNavigator_=function(){return goog.global.navigator};goog.labs.userAgent.util.userAgent_=goog.labs.userAgent.util.getNativeUserAgentString_();goog.labs.userAgent.util.setUserAgent=function(a){goog.labs.userAgent.util.userAgent_=a||goog.labs.userAgent.util.getNativeUserAgentString_()}" (assets/Script/Protobuf/google-protobuf.js:97:424)
at Object.goog.labs.userAgent.util.getNativeUserAgentString_ (assets/Script/Protobuf/google-protobuf.js:97:295)
at Object.require.google-protobuf (assets/Script/Protobuf/google-protobuf.js:97:453)
at s (file:///D:/WorkSpace/zergnest_client_creator/library/bundle.project.js?001:1:262)
    at file:///D:/WorkSpace/zergnest_client_creator/library/bundle.project.js?001:1:313
at Object.require.message_pb.google-protobuf (assets/Script/Protobuf/message_pb.js:8)
at s (file:///D:/WorkSpace/zergnest_client_creator/library/bundle.project.js?001:1:262)
    at file:///D:/WorkSpace/zergnest_client_creator/library/bundle.project.js?001:1:313
at Object.require.wssystem.message_pb (assets/Script/Frame/wssystem.js:3)
at s (file:///D:/WorkSpace/zergnest_client_creator/library/bundle.project.js?001:1:262)

**Comment by czlbaiyi** [comment]
你好，我是基于1.3版本添加的，暂时不支持1.4以及以上版本，有空时候我再来处理。
